spring:
  config:
    active:
      on-profile: heroku-db

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://us-cdbr-east-05.cleardb.net:3306/heroku_04ebd93eadb0a6a?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: b1516d9efd40a5
    password: 8e8ceb63

  jpa:
    hibernate:
      ddl-auto: none

  redis:
    host: redis-12335.c8.us-east-1-4.ec2.cloud.redislabs.com/redis-inf-cinema-11093811
    port: 12335

---
spring:
  config:
    active:
      on-profile: local-db

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create

  redis:
    host: localhost
    port: 6379

---
spring:
  config:
    active:
      on-profile: common-db

  jpa:
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
      open-in-view: true
